# Generated by Django 5.1.7 on 2025-04-04 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_song_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='is_public',
        ),
    ]
