# Generated by Django 5.2 on 2025-05-05 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_playlist_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
