# Generated by Django 5.2 on 2025-05-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_delete_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='song_videos/'),
        ),
        migrations.AddField(
            model_name='song',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
