# Generated by Django 5.2 on 2025-05-05 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_song_video_file_song_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='video_url',
        ),
    ]
